/**
 * LeadScout shared domain types.
 *
 * This file is the CONTRACT between all modules. Every module imports from
 * here and exports exactly the signatures documented in the "MODULE
 * CONTRACTS" section at the bottom. Do not edit this file from a module
 * task — if a contract can't be met, note it in your task result instead.
 */

export interface LatLng {
  lat: number;
  lng: number;
}

export interface ScanArea {
  center: LatLng;
  /** 100..50000 */
  radiusMeters: number;
}

export interface ScanRequest {
  area: ScanArea;
  /** Google Places (New) type strings, e.g. "restaurant". Empty = all defaults. */
  categories: string[];
  /** Safety cap on unique businesses fetched. Default 300. */
  maxBusinesses?: number;
  /** Parallel website audits. Default 5. */
  auditConcurrency?: number;
  /** Run PageSpeed Insights on each website (slow, ~30s/site). Default false. */
  psi?: boolean;
  /** Output directory root. Default "./leads". A timestamped subdir is created per scan. */
  outDir?: string;
  /**
   * Build a full pitch pack (mock page + one-pager + outreach + prompt) into a
   * per-lead subfolder for the top N leads. 0/undefined = flat MD files only.
   */
  pack?: number;
  /** Auto-draft each top lead's pitch via the local `ensemble` CLI (opt-in). */
  draft?: boolean;
}

export interface Business {
  /** Google Places resource id */
  id: string;
  name: string;
  address: string;
  phone?: string;
  /** E.164 form of phone (e.g. +919876543210), from phone.ts. */
  phoneE164?: string;
  /** https://wa.me/<digits> click-to-chat link, when a phone was parseable. */
  whatsappUri?: string;
  /** Email from the data source (OSM tags / Apify), before any site scrape. */
  email?: string;
  websiteUri?: string;
  googleMapsUri: string;
  rating?: number;
  ratingCount?: number;
  primaryType?: string;
  types: string[];
  /** OPERATIONAL | CLOSED_TEMPORARILY | CLOSED_PERMANENTLY */
  businessStatus?: string;
  location: LatLng;
  /**
   * 0..100 "establishment maturity" from data-source signal richness. Used as
   * a popularity proxy only when rating is absent (free OSM path). See score.ts.
   */
  maturity?: number;
}

export type WebsiteIssueId =
  | 'unreachable'
  | 'http-error'
  | 'no-https'
  | 'social-only'
  | 'no-title'
  | 'short-title'
  | 'no-meta-description'
  | 'not-mobile-friendly'
  | 'no-favicon'
  | 'no-h1'
  | 'no-og-tags'
  | 'no-structured-data'
  | 'stale-copyright'
  | 'outdated-tech'
  | 'slow-response'
  | 'heavy-page'
  | 'no-contact-method'
  | 'poor-psi-performance'
  | 'poor-psi-seo'
  | 'poor-accessibility'
  | 'poor-cwv-lcp'
  | 'poor-cwv-cls'
  | 'mixed-content'
  | 'insecure-headers'
  | 'broken-link'
  | 'dead-form'
  | 'stale-content'
  | 'js-rendered';

export interface WebsiteIssue {
  id: WebsiteIssueId;
  severity: 'critical' | 'major' | 'minor';
  /** Human sentence. Rendered verbatim in the lead MD file. */
  detail: string;
}

export interface WebsiteAudit {
  url: string;
  finalUrl?: string;
  reachable: boolean;
  httpStatus?: number;
  https: boolean;
  responseMs?: number;
  htmlBytes?: number;
  /** websiteUri points at Facebook/Instagram/WhatsApp/Linktree instead of a real site */
  socialOnly: boolean;
  issues: WebsiteIssue[];
  /** 0..100 — 100 is a healthy site. See score.ts for the healthy threshold. */
  score: number;
  /** Detected CMS/builder if any, e.g. "WordPress", "Wix" */
  tech?: string;
  psi?: PsiResult;
  /** Emails scraped from the page HTML (mailto: + plain text), deduped. */
  emails?: string[];
  /** True when the HTML is a JS-app shell — content-based issues are suppressed. */
  jsRendered?: boolean;
  /** Path (relative to the scan dir) of a saved mobile screenshot, if captured. */
  screenshotPath?: string;
}

export interface PsiResult {
  performance?: number;
  seo?: number;
  accessibility?: number;
  bestPractices?: number;
  /** Largest Contentful Paint, ms (lab). */
  lcpMs?: number;
  /** Cumulative Layout Shift (unitless). */
  cls?: number;
  /** Interaction to Next Paint, ms (lab/field). */
  inpMs?: number;
  /** Base64 JPEG of the mobile render, if returned. Never persisted to JSON. */
  screenshotBase64?: string;
}

export type LeadKind = 'no-website' | 'broken-website' | 'needs-improvement';

/** How hard this lead is likely to be to actually close. */
export type Winnability = 'easy' | 'medium' | 'hard';

export interface ScoreReason {
  label: string;
  /** Signed point contribution to leadScore. */
  points: number;
}

/** Estimated project value band, in INR. */
export interface ValueEstimate {
  low: number;
  high: number;
  /** Pre-formatted label, e.g. "₹15,000–40,000". */
  label: string;
}

/** Same-category competitive context within one scan, attached per lead. */
export interface CategoryContext {
  /** Businesses in the same category group in this scan. */
  total: number;
  /** Of those, how many already run a healthy website. */
  withHealthySite: number;
}

/** CRM lifecycle state for a business, persisted across scans (store.ts). */
export type LeadStatus =
  | 'new'
  | 'contacted'
  | 'interested'
  | 'won'
  | 'dead'
  | 'suppressed';

export interface Lead {
  kind: LeadKind;
  business: Business;
  /** Present unless the business has no website at all. */
  audit?: WebsiteAudit;
  /** 0..100 outreach priority. */
  leadScore: number;
  /** Itemised contributions that sum toward leadScore (for "why 82"). */
  scoreReasons: ScoreReason[];
  /** Concrete deliverables to sell them, human sentences. */
  needs: string[];
  /** Talking points for the pitch, human sentences. */
  pitchAngles: string[];
  /** Estimated project value band, if computable. */
  estValue?: ValueEstimate;
  /** How winnable this lead looks. */
  winnability?: Winnability;
  /** Same-category competitive context, set by the cross-lead pass in scan.ts. */
  context?: CategoryContext;
  /** CRM state merged in from the store at scan time (undefined = never seen). */
  status?: LeadStatus;
  /** True when this business id was not in the store before this scan. */
  isNew?: boolean;
  /** ISO timestamp of last recorded outreach, from the store. */
  lastContactedAt?: string;
  /** Free-text tags from the store. */
  tags?: string[];
}

export interface ScanResult {
  startedAt: string; // ISO
  finishedAt: string; // ISO
  area: ScanArea;
  categories: string[];
  /** Unique businesses found in the area. */
  totalFound: number;
  /** Businesses whose website was audited. */
  audited: number;
  /** Sorted by leadScore desc. */
  leads: Lead[];
  /** Businesses with a healthy website (not leads). */
  skipped: number;
  /** Leads whose business id was new (not in the CRM store) this scan. */
  newLeads?: number;
  /** Absolute paths of written files (per-lead MDs + SUMMARY.md + leads.json). */
  files: string[];
  /** Directory the files were written into. */
  outDir: string;
}

export type ProgressEvent =
  | { type: 'phase'; phase: 'search' | 'audit' | 'write'; message: string }
  | { type: 'search'; found: number; cell: number; cells: number }
  | { type: 'audit'; done: number; total: number; current: string }
  | { type: 'lead'; lead: Lead }
  | { type: 'done'; result: ScanResult }
  | { type: 'error'; message: string };

export type ProgressFn = (e: ProgressEvent) => void;

export type DataSource = 'google' | 'osm' | 'apify' | 'demo';

/**
 * Tunable scoring knobs. Externalised from score.ts so the user can re-rank an
 * existing leads.json without a re-scan and market-tune weights.
 */
export interface ScoringWeights {
  /** Audit-score issue penalties by severity. */
  severity: { critical: number; major: number; minor: number };
  /** Base lead score by kind before modifiers. */
  base: { 'broken-website': number; 'no-website': number; 'needs-improvement': number };
  /** Audit score at/above which a site counts as healthy (not a lead). */
  healthyThreshold: number;
  /** Max points from popularity (review count / maturity). */
  popularityCap: number;
  /** Reviews per popularity point. */
  reviewsPerPoint: number;
  /** Bonus when rating>=4.3 and >=20 reviews. */
  thrivingBonus: number;
  /** Penalty when businessStatus is not OPERATIONAL. */
  notOperationalPenalty: number;
  /** Bonus per unit of category value above baseline. */
  categoryValueBonus: number;
  /** Bonus per nearby same-category competitor that already has a healthy site. */
  competitorDensityBonus: number;
  /** Cap on the competitor-density bonus. */
  competitorDensityCap: number;
  /** Penalty for a national chain / franchise (they rarely buy local web work). */
  chainPenalty: number;
}

export interface AppConfig {
  /** From GOOGLE_MAPS_API_KEY. Absent => OSM Overpass (free) or demo. */
  googleApiKey?: string;
  /** From PAGESPEED_API_KEY, optional. PSI also works keyless at low volume. */
  pagespeedKey?: string;
  /** From APIFY_TOKEN. Enables the paid Apify Google-Maps data source. */
  apifyToken?: string;
  /** From APIFY_ACTOR_ID. Default 'compass/crawler-google-places'. */
  apifyActorId: string;
  /**
   * google = Places API (New, needs key) · osm = OpenStreetMap Overpass
   * (free, no key/card) · apify = paid scraper (needs token) · demo = fakes.
   * Precedence: google key > apify token > DEMO env > osm.
   */
  dataSource: DataSource;
  /** Convenience: dataSource === 'demo'. Demo fakes audits too, not just search. */
  demoMode: boolean;
  /** Active scoring weights (defaults from score.ts, overridable via .env JSON). */
  weights: ScoringWeights;
  /** From PORT. Default 4600. */
  port: number;

  /* ---- Production auth + billing (server.ts multi-tenant mode) ---- */
  /** HMAC secret for signed session cookies. Random per-boot in dev if unset. */
  sessionSecret: string;
  /** Send Secure cookies (true when APP_BASE_URL is https). */
  secureCookies: boolean;
  /** Public base URL, used for Cashfree return_url + cookie Secure flag. */
  appBaseUrl: string;
  /** Directory for auth/billing JSON stores (users/plans/subscriptions/orders). */
  dataDir: string;
  /** Seed admin email (default admin@leadscout.local). */
  adminEmail: string;
  /** Seed admin password. Admin is only created when this is set. */
  adminPassword?: string;
  /** Cashfree PG credentials + environment. */
  cashfreeAppId?: string;
  cashfreeSecretKey?: string;
  cashfreeEnv: 'sandbox' | 'production';
  /** Webhook signing secret (defaults to CASHFREE_SECRET_KEY). */
  cashfreeWebhookSecret?: string;
  /** Resolved Cashfree API base (sandbox vs production). */
  cashfreeBaseUrl: string;
}

/**
 * CRM record persisted per business id across scans (store.ts / .crm.json).
 */
export interface CrmRecord {
  id: string;
  status: LeadStatus;
  tags: string[];
  notes: { ts: string; text: string }[];
  followUpAt?: string;
  lastContactedAt?: string;
  suppressed: boolean;
  firstSeenScan?: string;
  lastSeenScan?: string;
  /** Enough of the Business to render pipeline/follow-up views without re-scan. */
  businessSnapshot: {
    name: string;
    phone?: string;
    email?: string;
    address?: string;
    kind?: LeadKind;
    leadScore?: number;
    mdFile?: string;
  };
}

export interface CategoryGroup {
  key: string;
  label: string;
  /** Google Places (New) type strings. */
  types: string[];
}

export interface CategoryGroup {
  key: string;
  label: string;
  /** Google Places (New) type strings. */
  types: string[];
}

/* ============================================================
 * MODULE CONTRACTS
 * ============================================================
 *
 * src/config.ts
 *   export function loadConfig(): AppConfig
 *     - Reads .env in the project root if present (tiny manual KEY=VALUE
 *       parser, no dotenv dep), then process.env wins.
 *     - dataSource: googleApiKey => 'google'; DEMO env truthy => 'demo';
 *       otherwise 'osm' (free OpenStreetMap Overpass).
 *
 * src/grid.ts
 *   export function gridCells(area: ScanArea, maxCellRadius?: number): ScanArea[]
 *     - Covers the requested circle with overlapping smaller circles
 *       (default maxCellRadius 800m) because Nearby Search caps at 20
 *       results per call. radius <= maxCellRadius => single cell.
 *     - Full coverage: every point in the big circle is inside >= 1 cell.
 *
 * src/places.ts
 *   export async function searchBusinesses(
 *     cfg: AppConfig, req: ScanRequest, onProgress?: ProgressFn
 *   ): Promise<Business[]>
 *     - demoMode => return mockBusinesses(...) from mock.ts.
 *     - Otherwise: Places API (New) searchNearby per (cell x category group),
 *       dedupe by id, respect req.maxBusinesses, emit 'search' progress.
 *
 * src/mock.ts
 *   export function mockBusinesses(area: ScanArea, categories: string[]): Business[]
 *   export function mockAudit(url: string): WebsiteAudit
 *     - Deterministic (hash of url/name, no randomness across runs).
 *     - Mix: ~40% no website, ~15% social-only links, ~10% broken site,
 *       rest real-looking sites whose mockAudit scores range healthy..poor.
 *
 * src/audit.ts
 *   export function isSocialUrl(url: string): boolean
 *   export function analyzeHtml(html: string, ctx: {
 *     finalUrl: string; https: boolean; responseMs: number; bytes: number;
 *   }): { issues: WebsiteIssue[]; tech?: string }
 *     - Pure, unit-testable.
 *   export async function auditWebsite(url: string, opts?: {
 *     pagespeedKey?: string; timeoutMs?: number; psi?: boolean;
 *   }): Promise<WebsiteAudit>
 *     - Never throws; failures become issues ('unreachable', 'http-error').
 *
 * src/score.ts
 *   export function auditScore(issues: WebsiteIssue[], psi?: WebsiteAudit['psi']): number
 *     - Maps issues to the 0..100 WebsiteAudit.score (audit.ts calls this).
 *   export function classifyLead(b: Business, audit?: WebsiteAudit): Lead | null
 *     - null => healthy website, not a lead.
 *     - Sets kind, leadScore, needs[], pitchAngles[]. Deterministic.
 *
 * src/markdown.ts
 *   export async function writeLeadFiles(
 *     result: Omit<ScanResult, 'files' | 'outDir'>, outDirRoot: string
 *   ): Promise<{ files: string[]; outDir: string }>
 *     - Creates <outDirRoot>/<yyyy-mm-dd-HHMM>-<lat>_<lng>/
 *     - One <slug>.md per lead with YAML frontmatter (name, kind, score,
 *       phone, address, maps, website) + business facts + audit findings +
 *       "What they need" + "Pitch angles" + suggested opener.
 *     - SUMMARY.md (table sorted by score desc, links to files) + leads.json.
 *
 * src/scan.ts
 *   export async function runScan(
 *     cfg: AppConfig, req: ScanRequest, onProgress?: ProgressFn
 *   ): Promise<ScanResult>
 *     - Orchestrates: searchBusinesses -> audit (concurrency pool,
 *       mockAudit when cfg.demoMode) -> classifyLead -> writeLeadFiles.
 *     - Emits every ProgressEvent type, ends with 'done'.
 *
 * src/server.ts
 *   - Express on cfg.port. Serves ./public static and ./leads static.
 *   - GET  /api/config      -> { demoMode, defaultCenter: {lat,lng} }
 *   - GET  /api/categories  -> CategoryGroup[]
 *   - POST /api/scan        -> text/event-stream of ProgressEvent as
 *                              "data: <json>\n\n" lines (client reads via
 *                              fetch body stream, not EventSource).
 *   - GET  /api/leads       -> list of past scan dirs + files under ./leads.
 *
 * src/cli.ts
 *   - tsx src/cli.ts --lat 12.97 --lng 77.60 --radius 2000
 *       [--categories food,retail] [--max 300] [--psi] [--out ./leads]
 *   - No --lat/--lng in demo mode => default center 12.9758,77.6045.
 *   - Prints progress lines and a final summary table to stdout.
 * ============================================================ */
